---
- name: Ubuntu | install prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_state }}"
    update_cache: true
    allow_unauthenticated: false
  register: _apt
  until: not _apt.failed
  retries: 3
  delay: 3
  loop: "{{ prereq_pkgs }}"
  become: true

- name: Ubuntu | add openstack repository
  ansible.builtin.command: >-
    add-apt-repository -y cloud-archive:{{ openstack_release }}
  become: true
  
- name: Ubuntu | install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_state }}"
    update_cache: true
    allow_unauthenticated: false
  register: _apt
  until: not _apt.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ packages }}"

- name: Ubuntu | disable apt auto upgrade
  ansible.builtin.copy:
    src: "{{ ansible_distribution | lower }}{{ item }}"
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  loop:
    - "/etc/apt/apt.conf.d/20auto-upgrades"
...
